### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by kresogalic8** [500tech/angular2-tree-component#200]
Hey guys, demo doesn't work on your getting started page.

**Comment by adamkleingit** [comment]
Fixed, thanks

**Comment by DenisVuyka** [comment]
Still not working

**Comment by karol-depka** [comment]
Hi.
Still not working. Now showing "404: Not Found" on https://angular2-tree.readme.io/docs .

**Comment by karol-depka** [comment]
Seems like this time the cause/symptoms are different.
